# Settings in this file will override values set in the Netlify UI.
# https://app.netlify.com/sites/tributedao/settings/deploys

# @note: The GH deploy workflows are not actually using context configs.
# Building and deploying with Netlify CLI doesn't use the same concept of
# automatic "production deploys", "branch deploys", and "deploy previews". But
# the GH deploy workflows are set up to mimic those categories. Their production
# builds are created with the relevant environment variables applied as if the
# context applied. Also, they are deployed with url aliases as if the context
# applied:

# production (push tag `v*`): https://tributedao.netlify.app
# develop (push to `main` branch): https://develop--tributedao.netlify.app
# deploy-preview (PR (non-draft) to `main` branch): https://deploy-preview-[PR#]--tributedao.netlify.app
