name: Netlify preview deployment

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: build
          key: build-preview-${{ hashFiles('**/build') }}

      - name: Create production build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: REACT_APP_ENVIRONMENT=development REACT_APP_INFURA_PROJECT_ID_DEV=${{ secrets.REACT_APP_INFURA_PROJECT_ID_DEV }} npm run build

      - name: Deploy to Netlify preview site
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --alias=deploy-preview-${{ github.event.pull_request.number }} --message='#${{ github.event.pull_request.number }}-${{ github.event.pull_request.title }}'
